# SITE CONFIGURATION
title: Rohit Sroch # your site title
author: rohit.iitr1994@gmail.com # You :P
description: > # Meta description of Homepage
  Hi there, I am Rohit Sroch 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rohitsroch.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Rohit Sroch
  links:
    - https://twitter.com/rohitsroch
    - https://www.facebook.com/rohitsroch
    - https://www.linkedin.com/in/rohitsroch
    - https://plus.google.com/+rohitsroch
    - https://github.com/rohitsroch
    #- https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Resume', link: '/resume'}
  - {name: 'Contact', link: '/contact'}

tagline: >
    Machine Learning Enthusiast
  
hero_avatar: avatar.jpg
hero_img: posts/emile-perron-190221_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: rohitsroch@gmail.com # email for form submission

twitter_username: rohitsroch # replace with your_twitter_username or comment to remove link from footer
github_username:  rohitsroch # replace with your_github_username or comment to remove link from footer
instagram_username: rohitsroch # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: https-rohitsroch-github-io  # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
